---
# janky 2017-11-13: the config file is now on an NFS share

  - name: condor config require local config file
    lineinfile:
      dest: /etc/condor/condor_config
      line: 'REQUIRE_LOCAL_CONFIG_FILE = true'
      regexp: '^ *REQUIRE_LOCAL_CONFIG_FILE *='

  - name: condor config set local config file name
    lineinfile:
      dest: /etc/condor/condor_config
      line: "LOCAL_CONFIG_FILE = /config/condor/condor_config.vgcn.{{ cloud }}"
      regexp: '^ *LOCAL_CONFIG_FILE *='

  - name: condor autodrain hack 1
    lineinfile:
      dest: /etc/rc.d/rc.local
      line: "( /bin/sleep {{ condor_drain_delay }} && /usr/bin/condor_drain -graceful `/bin/hostname` ) &"
      backup: yes

  - name: condor autodrain hack 2
    file: dest=/etc/rc.d/rc.local mode=a+x

  - name: condor service enable
    service:
      name: condor
      enabled: yes

  - name: condor walltime script
    copy:
      dest: /etc/condor/meta_walltime.py
      src:  meta_walltime.py
      mode: 0755

  - name: Disable firewalld
    systemd:
      name: firewalld
      enabled: no
      state: stopped
