---
- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - screen
    - ansible
    - vim
    - collectl
    - iotop
    - iftop
    - htop
    - atop
    - "@development"

- name: Ensure atop service and ensure it is started.
  systemd:
    name: atop
    enabled: yes
    state: started
