---
- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - screen
    - ansible
    - vim
    - collectl
    - iotop
    - iftop
    - htop
    - atop
    - mosh
    - libcgroup-tools
    - autofs
    - "@development"

- name: Ensure services are enabled + started
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - atop
    - autofs
