---
  - name: grub config
    replace:
      dest: /boot/grub/grub.conf
      regexp: 'rhgb quiet'
      replace: 'console=tty1 console=ttyS0'
    when: ansible_distribution_major_version == '6'

  - name: grub2 config
    lineinfile:
      dest: /etc/default/grub
      line: 'GRUB_CMDLINE_LINUX="crashkernel=auto console=tty1 console=ttyS0"'
      regexp: ^GRUB_CMDLINE_LINUX=
    when: ansible_distribution_major_version == '7'

  - name: grub2 generate boot file
    shell: grub2-mkconfig > /boot/grub2/grub.cfg
    when: ansible_distribution_major_version == '7'
