---
- lineinfile:
    path: /etc/group
    regexp: 'input:x:999:'
    line: 'input:x:500:'

- command: "find / -gid 999 -exec chgrp 500 '{}' +"
  ignore_errors: yes

- lineinfile:
    path: /etc/passwd
    regexp: 'polkitd:x:999:998:User for polkitd:/:/sbin/nologin'
    line: 'polkitd:x:500:998:User for polkitd:/:/sbin/nologin'

- command: "find / -uid 999 -exec chown 500 '{}' +"
  ignore_errors: yes

- name: galaxy account group
  group:
      name: galaxy
      state: present

- name: galaxy account user
  user:
    uid: "{{ galaxy_uid }}"
    name: galaxy
    group: galaxy
    home: /usr/local/galaxy
    state: present
    comment: Galaxy Service-Acct
    createhome: no

- name: 'disable selinux'
  command: setenforce Permissive

- command: 'ls -al /usr/local/'
  register: out
  ignore_errors: yes

- debug:
    var: out

- name: link to galaxy.
  file:
   src: "/data/gxmnt"
   dest: "/usr/local/galaxy"
   state: link
   force: yes

- name: link to tools
  file:
   src: "/data/tools"
   dest: "/usr/local/tools"
   state: link
   force: yes

- name: link to python
  file:
   src: "/data/python"
   dest: "/usr/local/python"
   state: link
   force: yes
