---
- lineinfile:
    path: /etc/group
    regexp: 'input:x:999:'
    line: 'input:x:500:'

- command: "find / -gid 999 -exec chgrp 500 '{}' +"
  ignore_errors: yes

- lineinfile:
    path: /etc/passwd
    regexp: 'polkitd:x:999:998:User for polkitd:/:/sbin/nologin'
    line: 'polkitd:x:500:998:User for polkitd:/:/sbin/nologin'

- command: "find / -uid 999 -exec chown 500 '{}' +"
  ignore_errors: yes

- name: galaxy account group
  group:
      gid: "{{ galaxy_gid }}"
      name: galaxy
      state: present

- name: galaxy account user
  user:
    uid: "{{ galaxy_uid }}"
    name: galaxy
    group: galaxy
    home: /usr/local/galaxy
    state: present
    comment: Galaxy Service-Acct
    createhome: no

- name: 'disable selinux'
  command: setenforce Permissive
