---
- name: galaxy account group, via shell
  shell: "grep -q ^galaxy: /etc/group || echo galaxy:x:{{ galaxy_gid }}: >> /etc/group"
  when: ansible_distribution_major_version == '7'

- lineinfile:
    path: /etc/group
    regexp: 'input:x:999:'
    line: 'input:x:500:'

- command: "find / -gid 999 -exec chgrp 500 '{}' +"
  ignore_errors: yes

- lineinfile:
    path: /etc/passwd
    regexp: 'polkitd:x:999:998:User for polkitd:/:/sbin/nologin'
    line: 'polkitd:x:500:998:User for polkitd:/:/sbin/nologin'

- command: "find / -uid 999 -exec chown 500 '{}' +"
  ignore_errors: yes

- name: galaxy account user
  when: ansible_distribution_major_version == '7'
  user:
    uid: "{{ galaxy_uid }}"
    name: galaxy
    group: galaxy
    home: /usr/local/galaxy
    state: present
    comment: Galaxy Service-Acct
    createhome: no

- name: Adding existing user galaxy to group docker
  user:
    name: galaxy
    groups: docker
    append: yes

- name: Adding existing user condor to group docker
  user:
    name: condor
    groups: docker
    append: yes

- name: link to galaxy.
  file:
   src: "/data/gxmnt"
   dest: "/usr/local/galaxy"
   state: link
   force: yes

- name: link to tools
  file:
   src: "/data/tools"
   dest: "/usr/local/tools"
   state: link
   force: yes

- name: link to python
  file:
   src: "/data/python"
   dest: "/usr/local/python"
   state: link
   force: yes
