---
  - name: galaxy account group, via shell
    shell: "grep -q ^galaxy: /etc/group || echo galaxy:x:{{ galaxy_gid }}: >> /etc/group"
    when: ansible_distribution_major_version == '7'

  - name: galaxy account user
    when: ansible_distribution_major_version == '7'
    user:
      uid: "{{ galaxy_uid }}"
      name: galaxy
      group: galaxy
      home: /usr/local/galaxy
      state: present
      comment: Galaxy Service-Acct
      createhome: no
      non_unique: yes
