# Setup for Virtual Jenkins Compute Node
---
- hosts: default

  vars:
    vg_build: 8
    vg_cluster: "vjcn"
    cloud: "jenkins"

  vars_files:
    - "group_vars/java.yml"

  roles:
    - basic
    - grub
    - cloudinit
    - packages
    - systemupdate
    - root
    - dynmotd
    - jenkins
    - dj-wasabi.telegraf
    - influxdata.chrony
    - geerlingguy.java
    - geerlingguy.docker
