# Setup for Virtual Galaxy central manager/NEMO version.
---
- hosts: default

  vars:
    cloud: bwCloud

  vars_files:
    - "group_vars/condor.yml"
    - "group_vars/central_manager.yml"
    - "group_vars/cloud-{{ cloud }}.yml"

  roles:
    - basic
    - cloudinit
    - htcondor
    - galaxy
    - systemupdate
    - dynmotd
    - dj-wasabi.telegraf
    - influxdata.chrony
