# Setup for Virtual Galaxy Compute Node (for NEMO with differing drain behaviour)
# This setup is valid for RHEL 7.x based systems.
---
- hosts: default

  vars:
    cloud: NEMO

  vars_files:
    - "group_vars/condor.yml"
    - "group_vars/cloud-{{ cloud }}.yml"

  roles:
    - packages
    - cloudinit
    - htcondor
    - galaxy
    - systemupdate
    - root
    - dynmotd
    - dj-wasabi.telegraf
    - influxdata.chrony
    - geerlingguy.java
    - geerlingguy.docker
