# Setup for Virtual Galaxy central manager/NEMO version.
---
- hosts: default

  vars:
    cloud: bwCloud

  vars_files:
    - "group_vars/condor.yml"
    - "group_vars/cloud-{{ cloud }}.yml"
    - "secret_group_vars/default.yml"

  roles:
    - basic
    - fixnetif
    - grub
    - sshserver
    - cloudinit
    - htcondor
    - htcondorcentral
    # janky: roced not needed on bwcloud
    #- roced
    - autofs
    - galaxy
    - packages
    - systemupdate
    - root
    - dynmotd-cocm
    # hxr: added for monitoring of the VMs
    #- dj-wasabi.telegraf
