# Setup for Virtual Galaxy Compute Node
# This setup is valid for RHEL 7.x based systems.
---
- hosts: default

  vars:
    cloud: bwCloud

  vars_files:
    - "group_vars/condor.yml"
    - "group_vars/cloud-{{ cloud }}.yml"
    - "secret_group_vars/default.yml"

  roles:
    - basic
    - grub
    - sshserver
    - cloudinit
    - htcondor
    - htcondorexec
    - autofs
    - galaxy
    - packages
    - systemupdate
    - root
    - dynmotd
    - dj-wasabi.telegraf
    - influxdata.chrony
    - geerlingguy.java
    - geerlingguy.docker
