# Setup for Virtual Galaxy central manager/NEMO version.
# This setup is valid for Redhat 7.x systems; Redhat 6.x
# systems need the roles 'grub1' 'galaxy' plus the
# 6.x-specific roles for cloud-init and Condor.
---
- hosts: default

  vars:
    cloud: bwCloud

  vars_files:
    - "group_vars/condor.yml"
    - "group_vars/cloud-{{ cloud }}.yml"
    - "secret_group_vars/default.yml"

  roles:
    - basic
    - fixnetif
    - grub2
    - sshserver
    - cloudinit
    - htcondor
    - htcondorcentral
    # janky: roced not needed on bwcloud
    #- roced
    - autofs
    - galaxy2
    - packages
    - systemupdate
    - root
    - dynmotd-cocm
    # hxr: added for monitoring of the VMs
    #- dj-wasabi.telegraf
