# Setup for Virtual Galaxy central manager/NEMO version.
---
- hosts: default

  vars:
    cloud: bwCloud

  vars_files:
    - "group_vars/condor.yml"
    - "group_vars/central_manager.yml"
    - "group_vars/cloud-{{ cloud }}.yml"

  roles:
    - basic
    - inhibit-point-upgrade
    - grub
    - cloudinit
    - htcondor
    - galaxy
    - packages
    - systemupdate
    - root
    - dynmotd
    - dj-wasabi.telegraf
    - influxdata.chrony
