# Setup for Virtual Galaxy central manager/NEMO version.
# This setup is valid for Redhat 6.x systems; Redhat 7.x
# systems need the roles 'grub2' and 'galaxy2' instead.
---
- hosts: default

  vars:
    cloud: NEMO

  vars_files:
    - "group_vars/condor.yml"
    - "group_vars/cloud-{{ cloud }}.yml"
    - "secret_group_vars/default.yml"

  roles:
    - basic
    - inhibit-point-upgrade-sl6x
    - fixnetif
    - grub1
    - sshserver
    - cloudinit
    - htcondor-6x
    - htcondorcentral-6x
    - roced
    - autofs
    - galaxy
    - packages
    - systemupdate
    - root
    - dynmotd-cocm
    # hxr: added for monitoring of the VMs
    #- dj-wasabi.telegraf
