# Setup for Virtual Jenkins Compute Node
---
- hosts: default

  vars:
    vg_build: 8
    cloud: "jenkins"

  vars_files:
    - "group_vars/all.yml"
    - "group_vars/java.yml"

  roles:
    - basic
    - systemupdate
    - dynmotd
    - jenkins
    - dj-wasabi.telegraf
    - influxdata.chrony
    - geerlingguy.java
    - geerlingguy.docker
    - geerlingguy.nodejs
    - y-yu.texlive
