# Setup for Virtual Galaxy Compute Node (for NEMO with differing drain behaviour)
# This setup is valid for RHEL 7.x based systems.
---
- hosts: default

  vars:
    condor_enable_autoshutdown: true
    # delay=24d grace=23h30m
    condor_drain_delay: 86400
    condor_drain_grace: 84600
    cloud: NEMO

  vars_files:
    - "group_vars/condor.yml"
    - "secret_group_vars/default.yml"

  roles:
    - basic
    - grub2
    - sshserver
    - cloudinit
    - htcondor
    - htcondorexec
    - autofs
    - galaxy2
    - packages
    - systemupdate
    - root
    - dynmotd
    # hxr: added for monitoring of the VMs
    - dj-wasabi.telegraf
