---
galaxy_uid: 999
galaxy_gid: 999
condor_local_config: /etc/condor/condor_config.local

central_manager: false
vg_build: 28
vg_cluster: "vgcn"
cloud: "default"

telegraf_agent_tags:
  - tag_name: datacenter
    tag_value: rz
  - tag_name: cluster
    tag_value: "{{ vg_cluster }}"
  - tag_name: cloud
    tag_value: "{{ cloud }}"
  - tag_name: vgcn_build
    tag_value: "{{ vg_build }}"
  - tag_name: distribution
    tag_value: "{{ ansible_distribution }}"
  - tag_name: distribution_version
    tag_value: "{{ ansible_distribution_version }}"

telegraf_plugins_default:
  - plugin: cpu
    config:
      - percpu = true
  - plugin: disk
  - plugin: diskio
  - plugin: mem
  - plugin: system
  - plugin: swap
  - plugin: net
  - plugin: netstat
  - plugin: processes
  - plugin: kernel
  - plugin: chrony
  - plugin: exec
    config:
      - commands = ["/bin/iamalive"]
      - name_suffix = "_alive"

java_packages:
 - java-1.8.0-openjdk
