---
  - name: cloud-init install
    package:
      name: cloud-init
      state: latest
      use: yum
# cloud-init

# janky 2016-12-07: this is an old bug that is patched in e.g. the version
# of cloud-init in the Ubuntu repos; for CentOS we have to do it ourselves.
# (the bug causes the instance to have a one hostname on initial bootup and
# another one on every subsequent boot)
  - name: cloud-init patch
    patch:
      src: "sl68-cloudinit.patch"
      dest: /usr/lib/python2.7/site-packages/cloudinit/distros/__init__.py
      backup: yes

  - name: cloud-init config 1
    blockinfile:
      dest: /etc/cloud/cloud.cfg
      backup: yes
      block: |
        system_info:
          default_user:
            name: centos
            gecos: CentOS Cloud User
            groups: [wheel, adm, systemd-journal]
            sudo: ["ALL=(ALL) NOPASSWD:ALL"]
            shell: /bin/bash
          distro: rhel
          paths:
            cloud_dir: /var/lib/cloud
            templates_dir: /etc/cloud/templates
          ssh_svcname: sshd

  - name: cloud-init config 2
    lineinfile:
      dest: /etc/cloud/cloud.cfg
      line: 'manage_etc_hosts: true'
      insertafter: '^syslog_fix_perms:.*$'
