---
# basic system setup
  - name: grub2 config
    lineinfile:
      dest: /etc/default/grub
      line: 'GRUB_CMDLINE_LINUX="crashkernel=auto console=tty1 console=ttyS0"'
      regexp: ^GRUB_CMDLINE_LINUX=
      backup: yes

  - name: grub2 generate boot file
    shell: grub2-mkconfig > /boot/grub2/grub.cfg
