---
  # special repo packages enable updating to the latest point release on SL
  # we don't want that for the central manager, so we remove it;
  # inhibiting point release upgrades  is not possible on CentOS,
  # so for CentOS this role becomes a big, fat NOP

  - name: yum-conf-sl6x removal
    when: ansible_distribution == 'Scientific' and ansible_distribution_major_version == '6'
    yum: name=yum-conf-sl6x state=absent

  - name: yum-conf-sl7x removal
    when: ansible_distribution == 'Scientific' and ansible_distribution_major_version == '7'
    yum: name=yum-conf-sl7x state=absent

  - name: 'NOTE: cannot inhibit point release upgrades on CentOS'
    when: ansible_distribution == 'CentOS'
    command: /bin/false
    ignore_errors: yes
