---
  - name: condor config
    template:
      src: local.j2
      dest: "{{ condor_local_config }}"

  - name: condor config require local config file
    lineinfile:
      dest: /etc/condor/condor_config
      line: 'REQUIRE_LOCAL_CONFIG_FILE = true'
      regexp: '^ *REQUIRE_LOCAL_CONFIG_FILE *='
      backup: yes

  - name: condor service enable
    service:
      name: condor
      enabled: yes

  - name: Disable firewalld
    when: ansible_distribution_major_version == '7'
    systemd:
      name: firewalld
      enabled: no
      state: stopped
