---
  - name: ssh key rsa2 private
    copy:
      dest: /etc/ssh/ssh_host_rsa_key
      mode: 0600
      owner: root
      group: root
      content: "{{ ssh_server_privkey }}"

  - name: ssh key rsa2 public
    copy:
      dest: /etc/ssh/ssh_host_rsa_key.pub
      mode: 0644
      owner: root
      group: root
      content: "{{ ssh_server_pubkey }}"

  - name: ssh server config 1
    lineinfile:
      dest: /etc/ssh/sshd_config
      line: '#HostKey /etc/ssh/ssh_host_ecdsa_key'
      regexp: '^ *HostKey  */etc/ssh/ssh_host_ecdsa_key'
      backup: yes

  - name: ssh server config 2
    lineinfile:
      dest: /etc/ssh/sshd_config
      line: '#HostKey /etc/ssh/ssh_host_ed25519_key'
      regexp: '^ *HostKey  */etc/ssh/ssh_host_ed25519_key'
      backup: no

