---
- name: dynmotd file
  template:
    src: dynmotd.sh.j2
    dest: /usr/bin/dynmotd

- name: fix permissions
  file:
    path: /usr/bin/dynmotd
    owner: root
    group: root
    mode: 0755

- name: add to profile
  lineinfile:
    path: /etc/profile
    line: "/usr/bin/dynmotd"
