---
  - name: epel install
    yum: name=epel-release.noarch state=present

  - name: yum-autoupdate removal
    yum: name=yum-autoupdate state=absent

  - name: patch util install
    yum: name=patch state=latest

  - name: lsof install
    yum: name=lsof state=latest

  - name: tcsh install
    yum: name=tcsh state=latest
